# Generated by Django 4.1.8 on 2023-04-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=500)),
                ('Restaurant', models.CharField(max_length=500)),
                ('CourseDescription', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('DishId', models.AutoField(primary_key=True, serialize=False)),
                ('DishName', models.CharField(max_length=500)),
                ('Restaurant', models.CharField(max_length=500)),
                ('Course', models.CharField(max_length=500)),
                ('recipe', models.CharField(max_length=3000)),
                ('taste', models.CharField(max_length=3000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('RestaurantId', models.AutoField(primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(max_length=500)),
                ('RestaurantIntro', models.CharField(max_length=2000)),
            ],
        ),
    ]
