# Generated by Django 4.1.8 on 2023-04-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantOwner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='taste',
            new_name='Taste',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='recipe',
        ),
        migrations.AddField(
            model_name='dishes',
            name='Rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
