# Generated by Django 4.1.8 on 2023-04-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantOwner', '0002_rename_price_dishes_price_rename_taste_dishes_taste_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
